### ISSUE TITLE
import pyTorch problem in notebook

### ISSUE THREAD

**Issue by bhick001** [HHalva/ccn#1]
I have successfully installed pytorch, however when I import it in notebooks it I get "ModuleNotFoundError: No module named 'torch'" error. 

I was able to import it in basic python (i.e. in the terminal) 
Any thoughts?

**Comment by HHalva** [comment]
Did you install pytorch using conda? Also, which system are you running?

**Comment by bhick001** [comment]
pip install torch torchvision torchaudio

OSX 10.15.7

Its just weird cause it is only for Jupiter notebooks not base python

**Comment by HHalva** [comment]
I am not sure why this happens, but seems like you are not the only one. 
I would strongly recommend using miniconda to always install all python packages, it seems like this has helped some people

https://github.com/pytorch/pytorch/issues/4827

**Comment by HHalva** [comment]
In fact, some seem to have had to even install jupyter via conda, so you might want to try that if install torch via miniconda doesnt help

https://github.com/pytorch/pytorch/issues/4827#issuecomment-370762721

**Comment by bhick001** [comment]
Installing pytorch with Conda solved the problem. I haven't ever had a problem like this with pip so that was something new
