### ISSUE TITLE
Week 2 question 4

### ISSUE THREAD

**Issue by kluopaja** [HHalva/ccn#2]
What does it mean to simulate the Game of Life by a Hopfield network?

**Comment by HHalva** [comment]
If you have a hopfield net and input some data into it, you are generating/simulating" sequence of patterns/outputs. Are you able to generate sequences such as those in game of life. You need to 1) think about the assumptions of the hopfield network 2) are some of the patterns in the game of life in contradiction with these assumptions.

**Comment by HHalva** [comment]
![image](https://user-images.githubusercontent.com/13895012/107230952-5d362e00-6a28-11eb-963c-d55dc8fc21c8.png)

**Comment by HHalva** [comment]
these patterns or one of them (see wikipedia for active gifs) may be good place to focus on. Hope this didnt make it too easy...
