### ISSUE TITLE
Equations 2.16 and 2.17

### ISSUE THREAD

**Issue by kluopaja** [HHalva/ccn#3]
I'm not sure if I understand the equations 2.16 and 2.17 correctly.

According to the 2.16 and 2.17 we would get the same amplitude and phase for signals
`C*cos(x) + S*sin(x)` and `-(C*cos(x) + S*sin(x))`
(as `sqrt(C*C + S*S) = sqrt((-C)*(-C) + (-S)*(-S))` and `-atan(S/C) = -atan((-S)/(-C))`)

**Comment by HHalva** [comment]
I have never really looked at these equations in detail ...but I think I may know where your confusion comes from. If you have both `C` and `S` negative, it essentially means that you have added `pi` to your phase, but if you do this, you get `-A*cos(wx+p)` as addding pi to cos does this. So you can see that this equation is negative of the (2.13) in the book and hence the equations that follow in the book would also have to accommodate this change in sign so you can't just take them for granted. Perhaps this is why `sgn(C)` in front of (2.16) would be more [precise](https://en.wikipedia.org/wiki/List_of_trigonometric_identities#Linear_combinations)?

**Comment by HHalva** [comment]
As far as I can tell, none of this is really necessary for the homework question..(in case someone else happens to read this and is confused).

**Comment by kluopaja** [comment]
Thanks
