### ISSUE TITLE
Week 4 Questions 1 and 2

### ISSUE THREAD

**Issue by kluopaja** [HHalva/ccn#5]
Question 1, part b, 3:
I'm not sure if I understand the question. The definition of PCA in the NIS book requires the principal components to be 
orthogonal (5.8).

Question 2:
Can I use np.random.laplace?

**Comment by HHalva** [comment]
I would say the book is not very clear in its use of terminology. How I mean it, and how imo it is rigorously defined is that there is a difference between principle components and principle component weights. They do make this distinction on page 100 (5.2.2.1).

yes, you can use np.random.laplace

**Comment by kluopaja** [comment]
Thanks
